import 'package:flutter/services.dart';
import '../ai/financial_context_engine.dart';

class ReportExportHelper {
  static String generateMarkdownReport(FinancialTelemetry telemetry) {
    final now = DateTime.now();
    final dateStr =
        '${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')}';

    final buffer = StringBuffer();
    buffer.writeln("# PocketLedger — AI Financial Telemetry Report");
    buffer.writeln("Generated: $dateStr | Engine: VALIXIS Gemini AI\n");
    buffer.writeln("---");
    buffer.writeln("## 1. Executive Summary");
    buffer.writeln(
      "- **Total Income:** \$${telemetry.totalIncome.toStringAsFixed(2)}",
    );
    buffer.writeln(
      "- **Total Expenses:** \$${telemetry.totalExpenses.toStringAsFixed(2)}",
    );
    buffer.writeln(
      "- **Net Balance:** \$${telemetry.netBalance.toStringAsFixed(2)}",
    );
    buffer.writeln(
      "- **Total Transactions:** ${telemetry.totalTransactionCount}\n",
    );

    buffer.writeln("## 2. Category Spending Breakdown");
    for (final cat in telemetry.topCategories) {
      final name =
          cat.categoryId.substring(0, 1).toUpperCase() +
          cat.categoryId.substring(1).replaceAll('_', ' ');
      final amount = (cat.totalInCents / 100.0).toStringAsFixed(2);
      buffer.writeln(
        "- **$name**: \$$amount (${cat.percentageOfTotal.toStringAsFixed(1)}%)",
      );
    }

    if (telemetry.anomalyAlerts.isNotEmpty) {
      buffer.writeln("\n## 3. Spending Anomalies & Warnings");
      for (final anomaly in telemetry.anomalyAlerts) {
        buffer.writeln("- ⚠️ $anomaly");
      }
    }

    buffer.writeln(
      "\n---\n*Report generated by PocketLedger AI Financial Engine*",
    );
    return buffer.toString();
  }

  static Future<void> copyReportToClipboard(
    FinancialTelemetry telemetry,
  ) async {
    final markdown = generateMarkdownReport(telemetry);
    await Clipboard.setData(ClipboardData(text: markdown));
  }
}
